project:
  type: website
  output-dir: docs

website:
  title: "Iacchei Lab"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - team.qmd
    tools: 
      - icon: instagram
        href: https://www.instagram.com/iaccheilab/?next=%2F
  back-to-top-navigation: true
  page-footer: 
    background: light
    right: 
      - icon: instagram
        href: https://www.instagram.com/iaccheilab/?next=%2F
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    smooth-scroll: true

editor: visual

